### ISSUE TITLE
Aici cred ca ruleaza la fiecare ora in minutul 9 secunda 0

### ISSUE THREAD

**Issue by alex-paltinean** [PasagerulPierdut/spring-core#1]
https://github.com/PasagerulPierdut/spring-core/blob/364680ab37c680a1f4e48b67298ea8150fbbe867/src/main/java/com/accenture/springcore/config/Scheduler.java#L15

**Comment by PasagerulPierdut** [comment]
Inlocuita cu varianta corecta: 0 0 9 1 * ? *
