### ISSUE TITLE
5 minute sunt 300000 milisecunde

### ISSUE THREAD

**Issue by alex-paltinean** [PasagerulPierdut/spring-core#2]
https://github.com/PasagerulPierdut/spring-core/blob/364680ab37c680a1f4e48b67298ea8150fbbe867/src/main/java/com/accenture/springcore/config/Scheduler.java#L24

**Comment by PasagerulPierdut** [comment]
Intentionat pusesem asa cand am facut verificarile, am schimbat acum conform cerintei temei.
