### ISSUE TITLE
Parametrii pot fi scosi intr-un obiect sa nu trimiti o lista lunga mai departe in Service

### ISSUE THREAD

**Issue by alex-paltinean** [PasagerulPierdut/spring-core#3]
https://github.com/PasagerulPierdut/spring-core/blob/364680ab37c680a1f4e48b67298ea8150fbbe867/src/main/java/com/accenture/springcore/controller/TransactionController.java#L37

**Comment by PasagerulPierdut** [comment]
Refactored to fit SortCriteriaInfo object.
