### ISSUE TITLE
Exceptiile custom ar trebui sa le extinzi din RuntimeException si atunci nu mai e nevoie de "throws"

### ISSUE THREAD

**Issue by alex-paltinean** [PasagerulPierdut/spring-core#5]
https://github.com/PasagerulPierdut/spring-core/blob/364680ab37c680a1f4e48b67298ea8150fbbe867/src/main/java/com/accenture/springcore/controller/TransactionController.java#L66

**Comment by PasagerulPierdut** [comment]
Refactorizate.
