### ISSUE TITLE
Lipseste tratarea exceptiei Exception, daca e sa crape undeva cu ceva netratat nu o sa raspunda in formatul definit de tine

### ISSUE THREAD

**Issue by alex-paltinean** [PasagerulPierdut/spring-core#6]
https://github.com/PasagerulPierdut/spring-core/blob/364680ab37c680a1f4e48b67298ea8150fbbe867/src/main/java/com/accenture/springcore/exception/handler/RestExceptionHandler.java#L17

**Comment by PasagerulPierdut** [comment]
Tratarea adaugata.
