### ISSUE TITLE
Filtrarea dupa confirmed poate fi mutata in repo

### ISSUE THREAD

**Issue by alex-paltinean** [PasagerulPierdut/spring-core#8]
https://github.com/PasagerulPierdut/spring-core/blob/364680ab37c680a1f4e48b67298ea8150fbbe867/src/main/java/com/accenture/springcore/service/TransactionService.java#L73

**Comment by PasagerulPierdut** [comment]
Moved.

**Comment by PasagerulPierdut** [comment]
Mutata.
